# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'trackMate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for trackMate
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/RemoteConfig'

  target 'trackMateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
